default:
  image: node:latest

stages:
  - lint
  - codequality
  - sonarscanner
  - test
  - deploy

Lint:
  stage: lint
  script:
    - npm ci
    - npm run lint

include:
  - template: Code-Quality.gitlab-ci.yml

CodeQuality:
  stage: codequality
  artifacts:
    paths: [gl-code-quality-report.json]

SonarScanner:
  image:
    name: sonarsource/sonar-scanner-cli:4.6
    entrypoint: [""]
  stage: sonarscanner
  script:
    - sonar-scanner
      -Dsonar.projectKey=$SONARQUBE_PROJECT_KEY
      -Dsonar.host.url=https://sonarqube.cs.ui.ac.id/
      -Dsonar.login=$SONARQUBE_TOKEN
  only:
    - staging

Test:
  stage: test
  script:
    - npm ci
    - npm run build
    - npm run test
  coverage: /All\sfiles.*?\s+(\d+.\d+)/

DeployStaging:
  stage: deploy
  only:
    - staging
  
  environment:
    name: staging

  script:
    - npm i -g vercel
    - DEPLOYMENT_URL=$(VERCEL_ORG_ID=$VERCEL_ORG_ID VERCEL_PROJECT_ID=$VERCEL_PROJECT_ID_STAGING vercel --confirm -t $VERCEL_TOKEN --prod)

DeployProduction:
  stage: deploy
  only:
    - master
  
  environment:
    name: production

  script:
    - npm i -g vercel
    - DEPLOYMENT_URL=$(VERCEL_ORG_ID=$VERCEL_ORG_ID VERCEL_PROJECT_ID=$VERCEL_PROJECT_ID_PRODUCTION vercel --confirm -t $VERCEL_TOKEN --prod)
