default:
  image: node:latest

variables:
  VERCEL_ORG_ID: $VERCEL_ORG_ID

.base_rules: &base_rules
  only:
    - merge_requests
    - staging
    - master

stages:
  - lint
  - test
  - deploy

Lint:
  <<: *base_rules
  stage: lint
  script:
    - npm ci
    - npm run lint

Test:
  <<: *base_rules
  stage: test
  script:
    - npm ci
    - npm run build
    - npm run test
  coverage: /All\sfiles.*?\s+(\d+.\d+)/

SonarScanner:
  image:
    name: sonarsource/sonar-scanner-cli:4.6
    entrypoint: [""]
  stage: test
  needs: ['Test']
  script:
    - sonar-scanner
      -Dsonar.projectKey=$SONARQUBE_PROJECT_KEY
      -Dsonar.host.url=https://pmpl.cs.ui.ac.id/sonarqube
      -Dsonar.branch.name=$CI_COMMIT_REF_NAME
      -Dsonar.branch.target=$CI_MERGE_REQUEST_TARGET_BRANCH_NAME
      -Dsonar.login=$SONARQUBE_TOKEN
      -Dsonar.qualitygate.wait=true
      -Dsonar.javascript.lcov.reportPaths=coverage/lcov.info
  only:
    - merge_requests

DeployStaging:
  stage: deploy
  only:
    - staging
  
  environment:
    name: staging
  
  variables:
    VERCEL_PROJECT_ID: $VERCEL_PROJECT_ID_STAGING

  script:
    - npm i -g vercel
    - vercel --confirm -t $VERCEL_TOKEN --prod

DeployProduction:
  stage: deploy
  only:
    - master
  
  environment:
    name: production
  
  variables:
    VERCEL_PROJECT_ID: $VERCEL_PROJECT_ID_PRODUCTION

  script:
    - npm i -g vercel
    - vercel --confirm -t $VERCEL_TOKEN --prod
