# Generated by Django 4.0.3 on 2022-04-19 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('klinik', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lamaranpasien',
            name='email',
            field=models.EmailField(default='notempty@email.com', max_length=254),
            preserve_default=False,
        ),
    ]
