# Generated by Django 4.0.3 on 2022-05-18 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('klinik', '0002_lamaranpasien_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='lamaranpasien',
            name='nama',
            field=models.CharField(default='anon', max_length=100),
            preserve_default=False,
        ),
    ]
