# Generated by Django 4.0.3 on 2022-03-06 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('klinik', '0003_alter_klinik_owner'),
        ('klinik', '0003_klinik_sik'),
    ]

    operations = [
    ]
