# Generated by Django 4.0.3 on 2022-03-06 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("klinik", "0005_alter_klinik_owner"),
    ]

    operations = [
        migrations.AlterField(
            model_name="klinik",
            name="sik",
            field=models.FileField(upload_to=""),
        ),
    ]
