# Generated by Django 4.0.3 on 2022-03-07 04:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("klinik", "0006_alter_klinik_sik"),
    ]

    operations = [
        migrations.AlterField(
            model_name="klinik",
            name="owner",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="klinik.ownerprofile"
            ),
        ),
    ]
