# Generated by Django 4.0.3 on 2022-03-08 16:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('klinik', '0006_alter_klinik_sik'),
    ]

    operations = [
        migrations.CreateModel(
            name='StafProfile',
            fields=[
                ('profile_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='klinik.profile')),
            ],
            bases=('klinik.profile',),
        ),
    ]
