<<<<<<< HEAD
# Generated by Django 4.0.3 on 2022-03-13 06:24
=======
# Generated by Django 4.0.3 on 2022-03-13 06:51
>>>>>>> 959d779129c2c2d91f891eca1fb891d5b1801586

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('klinik', '0007_alter_klinik_owner'),
        ('klinik', '0010_stafprofile_cabang'),
    ]

    operations = [
    ]
