# Generated by Django 4.0.3 on 2022-03-13 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("klinik", "0007_alter_klinik_owner"),
        ("klinik", "0010_stafprofile_cabang"),
    ]

    operations = []
